name: Python Build (x86_64 on Plucky)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for x86_64
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Switch to Plucky and Full Upgrade System
      run: |
        echo "### Changing APT sources from noble to plucky..."
        sudo sed -i 's/noble/plucky/g' /etc/apt/sources.list
        # The following command may fail if no lists are in the .d directory, so we add a failsafe
        sudo sed -i 's/noble/plucky/g' /etc/apt/sources.list.d/*.list || echo "No files in sources.list.d to modify."
        
        echo "### Updating package lists from plucky repositories..."
        sudo apt-get update
        
        echo "### Performing full system upgrade to plucky..."
        sudo DEBIAN_FRONTEND=noninteractive apt-get full-upgrade -y
        
        echo "### System upgrade complete."

    - name: Setup Python 3.13 for x64
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        architecture: 'x64'

    - name: Install build dependencies
      run: |
        sudo apt-get install -y clang mold

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow nuitka

    - name: Compile module with Nuitka
      run: |
        LDFLAGS="-fuse-ld=mold" python -m nuitka \
          --module \
          --clang \
          --lto=yes \
          main.py
    
    - name: Rename artifact for upload
      run: mv main.*.so main-x86_64.so

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-module-x86_64
        path: main-x86_64.so
