name: Python Build (x86_64)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for x86_64
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python 3.13 for x64
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'
        architecture: 'x64'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang mold

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow nuitka

    - name: Compile module with Nuitka
      run: |
        LDFLAGS="-fuse-ld=mold" python -m nuitka \
          --module \
          --clang \
          --lto=yes \
          main.py
    
    - name: Rename artifact for upload
      run: mv main.*.so main-x86_64.so

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-module-x86_64
        path: main-x86_64.so
