name: Python Build (x86_64 on Plucky with Latest Clang)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for x86_64
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare System Environment (Global Plucky Upgrade with Exceptions)
      run: |
        echo "### 1. Applying 'noble' -> 'plucky' replacement with exceptions..."
        sudo sed -i 's/noble/plucky/g' /etc/apt/sources.list
        for f in /etc/apt/sources.list.d/*; do
          if [ -f "$f" ]; then
            if [[ "$f" == *azure-cli* ]]; then
              echo "-> Skipping Azure CLI repository: $f"
              continue
            fi
            if [[ "$f" == *microsoft-prod* ]]; then
              echo "-> Applying Microsoft repo fix to $f (24.04->25.04, noble->plucky)"
              sudo sed -i 's/ubuntu\/24.04\/prod/ubuntu\/25.04\/prod/g' "$f"
              sudo sed -i 's/noble/plucky/g' "$f"
              continue
            fi
            echo "-> Applying general noble->plucky replacement to $f"
            sudo sed -i 's/noble/plucky/g' "$f"
          fi
        done

        echo "### 2. Adding the LLVM APT repository for 'plucky'..."
        sudo apt-get update && sudo apt-get install -y gnupg wget
        sudo mkdir -p /etc/apt/keyrings
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/llvm-snapshot.gpg
        echo "deb [signed-by=/etc/apt/keyrings/llvm-snapshot.gpg] http://apt.llvm.org/plucky/ llvm-toolchain-plucky main" | sudo tee /etc/apt/sources.list.d/llvm.list

        echo "### 3. Updating package lists for the new environment..."
        sudo apt-get update
        
        echo "### 4. Performing full system upgrade to 'plucky'..."
        sudo DEBIAN_FRONTEND=noninteractive apt-get -o Dpkg::Options::="--force-confold" full-upgrade -y
        
        echo "### 5. Installing clang, mold, and specific LLVM linker tools..."
        # THE FIX: Install the specific package for the linker plugin.
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y clang mold llvm-22-linker-tools
        clang --version

    - name: Setup Python 3.13 for x64
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow nuitka

    - name: Compile module with Nuitka
      run: |
        LDFLAGS="-fuse-ld=mold" python -m nuitka \
          --module \
          --clang \
          --lto=yes \
          main.py
    
    - name: Rename artifact for upload
      run: mv main.*.so main-x86_64.so

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-module-x86_64
        path: main-x86_64.so
